### ISSUE TITLE
Images Cutted - Outlook 365

### ISSUE THREAD

**Issue by baltazaroliveira** [mjmlio/mjml#2154]
**Describe the bug**
The images in Outlook are cutted.

**To Reproduce**
1. Create a file with this MJML code: `<mjml>...</mjml>`

`
    <mj-section>

      <mj-column>
        <mj-image width="50px" height="50px" src="https://www.heliotextil.com/pac_si/imgs/canais_digitais.png"></mj-image>
        <mj-text font-size="18px" align="center">
          Canais Digitais
        </mj-text>
        <mj-text font-size="12px" align="center" height="35px">
          Descubra os benefícios de estar conectado digitalmente e autorize o pré-registo com o seu e-mail.
        </mj-text>
        <mj-button inner-padding="0px" width="94px" height="21px" font-size="12px" href="https://www.heliotextil.com/pac_si/docs/pt/funcionalidades_do_site.pdf" background-color="#F4EFEA" border-radius="5px"
          border="1px solid #4D4D4D">
          Clique Aqui
        </mj-button>
      </mj-column>

      
      <mj-column>
        <mj-image width="50px" height="50px" src="https://www.heliotextil.com/pac_si/imgs/suporte_personalizado.png"></mj-image>
        <mj-text font-size="18px" align="center">
          Suporte Personalizado
        </mj-text>
        <mj-text font-size="12px" align="center" height="35px">
          Conheça o nosso serviço a cliente e disponha de um atendimento personalizado.<br><br>
        </mj-text>
        <mj-button inner-padding="0px" width="94px" height="21px" font-size="12px" href="https://www.heliotextil.com/pt/contactos#contactos" background-color="#F4EFEA" border-radius="5px"
          border="1px solid #4D4D4D">
          Clique Aqui
        </mj-button>
      </mj-column>

    </mj-section>`

![image](https://user-images.githubusercontent.com/953742/105701165-cf275700-5f01-11eb-9b80-01a522d6d66c.png)

**Expected behavior**
Images don´t being cutted

(in browser)
![image](https://user-images.githubusercontent.com/953742/105701417-2a594980-5f02-11eb-9508-a386ea729c99.png)

**MJML environment (please complete the following information):**

Windows

 - MJML Version [e.g. 4.2.0]

![image](https://user-images.githubusercontent.com/953742/105701250-eebe7f80-5f01-11eb-9633-b8dc5d180714.png)

 - MJML tool used [e.g MJML App]

MJML

**Affected email clients (for rendering issues):**

Outlook 365

If i set a cellpadding in table the images don´t cut, but don´t have that option in mj-section.

**Comment by baltazaroliveira** [comment]
Or if i don´t set cellpadding also works fine...

![image](https://user-images.githubusercontent.com/953742/105702170-4ad5d380-5f03-11eb-8ca4-410a28228b1b.png)

**Comment by kmcb777** [comment]
Hi @baltazaroliveira i couldn't reproduce the issue, with your mjml code here is the emailonacid preview for Outlook365 : 
![image](https://user-images.githubusercontent.com/8144509/107659042-07ab8c80-6c87-11eb-92fd-8afc0c1a65ff.png)
Which way do you send the email ? Could you try sending it with https://putsmail.com/tests/new ?

**Comment by baltazaroliveira** [comment]
Hi @kmcb777,

I am using Outlook. I created and email in MJML, generate the HTML file and try to view in Word and Outlook (they use same engine) and I have that problem.

![image](https://user-images.githubusercontent.com/953742/107777793-3b47ee80-6d3b-11eb-92bf-b2d35d44d36a.png)

If using PutsMail, it's Ok. I have copied the HTML of that email to a new file. Open in Outlook and same problem.

Result in PutsMail HTML

![image](https://user-images.githubusercontent.com/953742/107777998-70544100-6d3b-11eb-8f07-f492f1c87a9c.png)

**Same HTML** in Word/Outlook

![image](https://user-images.githubusercontent.com/953742/107778177-a396d000-6d3b-11eb-9ef1-ee221071407b.png)

It is possible to set that value "automatically", or not set at all?

Thanks,
Baltazar

**Comment by kmcb777** [comment]
If you opened the html file directly with outlook, I don't know if outlook alters the html differently than usual.
If it's ok when you send with putsmail then open it in outlook, that means your html is ok. Is that what you tried with putsmail ?
If it's ok when you do it like this, then the recipients shouldn't have this issue either, as long as you send the email in a way that does not alter the html (sending with outlook does).
Since it's fine on emailonacid test, it should be ok this way.

And if you really need to set an attribute manually on a specific html element, your can use `mj-html-attributes`

**Comment by baltazaroliveira** [comment]
The html is the same, open that html in Outlook cause the problem of cutted images.

It´s Ok in putsmail. I have to send with Outlook. We have an "automatic" process to send the email.

Do you have a concrete example of _mj-html-attributes_ to change the **cellpadding** to another value?

I think that issue should be resolved.. All the persons using Outlook to send email will have the same problem that I have.

**Comment by GarryFlemings** [comment]
> All the persons using Outlook to send email will have the same problem that I have.

You're right. Sadly, they'll have many other problems, too.

It's not clear here that you understand a point kcmb777 is making. Sadly, authors of email clients (like Outlook) have reasons for altering the HTML you paste into the clients for sending. Outlook changes the email you paste into it.

Indeed, if you find an email client that doesn't change the email, please share! A lot of MJML users would want to know! I've never heard of one, but I don't have the experience kmcb777 has.

The best way to get your HTML to your readers is to send it through an ESP that doesn't change the HTML. (Some ESPs, like email clients, change the HTML before sending. Not Putsmail.)

An automated process sounds great! Maybe ... send the output to your preferred ESP? Good luck!

**Comment by baltazaroliveira** [comment]
Hi @GarryFlemings,

Thanks for your opinion.

Only issue that have with Outlook and MJML is what I have described (images cutted).

If it is possible in MJML to have an option to change cellpadding(or not set at all) in mj-section, the problem is resolved for me and anothers that use Outlook as "main" sender. 

I have this automated process in a lot of automated process using Outlook with no problem.

I have to use Outlook...

It is possible to MJML have a option to change change cellpadding(or not set at all) in mj-section?

Baltazar

**Comment by iRyusa** [comment]
We won't do that as the mail you send via Outlook won't be responsive anymore, so it doesn't fix the underlying issue that Outlook will alter the HTML.

There's no real issue with those value as they are needed to ensure it will render fine for every clients.

I'm not sure that mj-html-attributes would allow to reset value to empty string but you should read this and try it https://documentation.mjml.io/#mj-html-attributes

**Comment by baltazaroliveira** [comment]
For me it is an issue and should give an option to add that option. Closing this issue create a problem for all the person who use Outlook as sender.

**Comment by kmcb777** [comment]
Unfortunately as GarryFlemings said, even if for your use case removing this `cellpadding` solves your issue, you'll get multiple other issues with most mjml components if you send with outlook anyway.
Making all mjml components usable in an email sent via outlook is just not possible. i.e. as iryusa said, mj-columns couldn't be responsive anymore.
You can't imagine all that's done already in mjml just to make emails display correctly in outlook, it's about 1/4 of the html output

**Comment by baltazaroliveira** [comment]
I have no option, I have to send in Outlook.

I understand you answer, but for me it is very strange that MJML don't work this way (Outlook way).

@kmcb777 Thanks for your feedback.

**Comment by blanzh** [comment]
Hi everyone!
Any news? Last native email client Windows 10

**Comment by GarryFlemings** [comment]
It would be a huge surprise if the MJML team starts to support sending HTML via any email client. We all face problems enough when we send via ESPs that guarantee they're sending the HTML we write.

Maybe MJML could be part of your development process. Maybe tweaking the HTML as you need it after it comes out of MJML would be quicker than writing the HTML from scratch.

A lot of us here would recommend your company choose to send its emails through an ESP (web search for Email Service Provider) that doesn't change your HTML. MJML is separate from all ESPs (even MailJet, despite MailJet having started this open source project). Many ESPs give you a great deal more value than just sending your email. Higher deliverability (less routing to SPAM folders). Lists of who opened the email. Expert help in your local language. Lots more.

Here are some links from a web search, "why use an email service provider" (haven't read them; no endorsements of articles or providers)

- http://blog.clickdimensions.com/8-smart-reasons-use-email-service-provider/
- https://www.businessblogshub.com/2018/05/why-use-an-email-service-provider/
- https://www.linkedin.com/learning/asp-dot-net-core-communication-management/why-use-an-email-service
