### ISSUE TITLE
v4.10.0 is breaking our app

### ISSUE THREAD

**Issue by ddolcimascolo** [mjmlio/mjml#2299]
**Describe the bug**

Our build starts to fail while updating mjml to v4.10.0

**To Reproduce**

Upgrade to v4.10.0 from v4.9.3

**Expected behavior**

Our builds still pass, and emails are rendered :+1: 

**MJML environment (please complete the following information):**

 - OS: Ubuntu 20.04
 - MJML Version 4.10.0
 - MJML tool used [e.g MJML App]: The MJML API

**Additional context**

```
/builds/stordata/cmdb/node_modules/mjml-core/lib/index.js:66
var _classCallCheck2 = _interopRequireDefault(require("@babel/runtime/helpers/classCallCheck"));
                       ^
TypeError: _interopRequireDefault is not a function
    at Object.<anonymous> (/builds/stordata/cmdb/node_modules/mjml-core/lib/index.js:66:24)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.replacementCompile (/builds/stordata/cmdb/node_modules/append-transform/index.js:60:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.<anonymous> (/builds/stordata/cmdb/node_modules/append-transform/index.js:64:4)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/builds/stordata/cmdb/node_modules/mjml/lib/index.js:12:41)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.replacementCompile (/builds/stordata/cmdb/node_modules/append-transform/index.js:60:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.<anonymous> (/builds/stordata/cmdb/node_modules/append-transform/index.js:64:4)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/builds/stordata/cmdb/backend/mailer.js:2:390)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.replacementCompile (/builds/stordata/cmdb/node_modules/append-transform/index.js:60:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
```

Looking at https://app.renovatebot.com/package-diff?name=mjml&from=4.9.3&to=4.10.0 I can see this 
![image](https://user-images.githubusercontent.com/5468291/122427572-8431dd00-cf91-11eb-94d0-d8ad908e837d.png)

I suppose that's not what you want :)

**Comment by ddolcimascolo** [comment]
Sorry for the initial empty issue :sweat_smile: I misclicked...

**Comment by ddolcimascolo** [comment]
Hey guys, am I alone on this one? Any other information I can provide to help troubleshoot the issue?

**Comment by iRyusa** [comment]
We’ll take a look at this. That’s weird we didn’t change the build process 🤔

Stay on 4.9.x for now

**Comment by ddolcimascolo** [comment]
Thx @iRyusa! Yep, canceling the update for now.

**Comment by MartinJohns** [comment]
We have the same issue, builds suddenly breaking due to the updated version. We will pin the version for now.

**Comment by iRyusa** [comment]
It appears to work on a fresh install to me tho 🤔 Can you try to clean out your lock files and node modules ?

**Comment by iRyusa** [comment]
@MartinJohns @ddolcimascolo What version of Node are you running ?

**Comment by MartinJohns** [comment]
We're running Node `12.13` via the Docker image `node:12.13-alpine`.  
The builds succeed, but the tests via Jest have failed:

    TypeError: _interopRequireDefault is not a function

    const mjml2html: typeof _mjml2html = require('mjml');

Our `tsconfig.json` has nothing special configured:

    {
      "compilerOptions": {
        "module": "commonjs",
        "declaration": true,
        "removeComments": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "target": "es2017",
        "sourceMap": true,
        "outDir": "./dist",
        "baseUrl": "./",
        "incremental": true,
        "noImplicitAny": true
      },
      "exclude": ["node_modules", "dist"]
    }

**Comment by ddolcimascolo** [comment]
> @MartinJohns @ddolcimascolo What version of Node are you running ?

Node 14.15. My context if a CI run so running `npm ci` beforehand, which installs everything fresh in an empty node_modules folder

**Comment by iRyusa** [comment]
Can you both try to add @babel/runtime to test if it fix the error at least ? And can you both post your yarn.lock / package-lock.json ?

**Comment by ddolcimascolo** [comment]
@iRyusa I also tried on a fresh install and it works fine, I think I know why.

A fresh install installs `@babel/runtime` 7.14 as per the screenshot below  
![image](https://user-images.githubusercontent.com/5468291/122559654-e9dca280-d03f-11eb-9f91-e75c80d596c1.png)

This is so because of the lax versioning you have in [package.json](https://github.com/mjmlio/mjml/blob/master/package.json#L17) `^7.8.7` so it simply gets the latest 7.x version

When upgrading, my locked version of `@babel/runtime` (7.12.5) also satisfies your required version, so npm does not upgrade it.  
![image](https://user-images.githubusercontent.com/5468291/122559933-4049e100-d040-11eb-8ee1-b5178fb4060c.png)

Unfortunately, mjml now depend on a version of `@babel/runtime` that introduced this `.default` I highlighted above, probably 7.14 but this needs to be verified.

**Comment by ddolcimascolo** [comment]
So you should either revert the change that introduced the dependency on the new `@babel/runtime`, or bump your minimum required version of it in package.json.

**Comment by iRyusa** [comment]
We'll upgrade those deps in next minor @MartinJohns are you able to fix it too then ?

**Comment by doits** [comment]
I can confirm that deleting `yarn.lock` and reinstalling all dependencies, which then seems to fetch the latest version of all deps including `@babel/runtime` `7.14.6`, fixes the problem in existing apps.

**Comment by ddolcimascolo** [comment]
Thx @doits for the PR! Looking forward for a new release to test the dependency upgrade

**Comment by JacobLey** [comment]
I agree this was originally fixed with #2301 and version v4.10.1, but it appears to have popped up again? I just re-installed dependencies locally and error started happening. I also noticed in on my CI builds.

Was the source-code for 4.10.1 updated without upping the version number?

https://npm.runkit.com/mjml try throwing a console.log before/after and you will see it fails. Appears to be same error of `_interopRequireDefault is not a function`

**Comment by ddolcimascolo** [comment]
Yeah... 4.10.1 did not make it for us either.

For the record, I ended up manually bumping @babel/runtime in package-lock.json. I know it's weird to do that, but I couldn't block my dependencies management process any longer...

Cheers, 
David

**Comment by doits** [comment]
I'm using yarn and at least it is correctly listed as a dependency:

```
"mjml@npm:^4.10.1":
  version: 4.10.1
  resolution: "mjml@npm:4.10.1"
  dependencies:
    "@babel/runtime": ^7.14.6
```

Maybe it is an npm issue? Maybe npm must be used with a flag to update dependencies of dependencies, too?

**Comment by iRyusa** [comment]
Weird that you still have that issue i've tried locally to upgrade from an older 4.7.x to a 4.10.1 and it worked just fine with yarn and npm. Probably a lockfile issue on your end then

**Comment by JacobLey** [comment]
Bumping `@babel/runtime` directly in my package appeared to work (declaring a dev dependency on `"@babel/runtime": "7.14.6"`) and then removing it.

That means mjml requires such a recent version, but does not declare it explicitly. mjml packages should be updated to require this newer version.

https://github.com/mjmlio/mjml/blob/master/packages/mjml-core/package.json#L25
The dependency declares `^7.8.7` and I personally was on `7.11.2` (passes). But apparently that is invalid, and really it needs something like `7.14.6` for correct usage.

Each mjml package that depends on the runtime should be updated accordingly.

**Comment by iRyusa** [comment]
Mh. We did merge the PR on mjmlpackage but didn’t bump on every package tho you’re right. It’s weird that npm won’t satisfy mjml required version on update.

**Comment by doits** [comment]
> It’s weird that npm won’t satisfy mjml required version on update

Maybe `@babel/runtime` must be a [peerDependency](https://nodejs.org/es/blog/npm/peer-dependencies/), so only one compatible version is installed and not multiple, incompatible ones?

**Comment by doits** [comment]
In the meantime I updated the dep on all packages in #2332, I hope this makes sure that at least mjml is using the same babel runtime version even if the main app is using a different one

**Comment by ddolcimascolo** [comment]
Thx !
